version: "2"

linters:
  default: none
  enable:
    - govet
    # TODO: enable after fixing violations
    # - errcheck     # https://github.com/eugenioenko/ttt/issues/505
    # - staticcheck  # https://github.com/eugenioenko/ttt/issues/506
    # - ineffassign  # https://github.com/eugenioenko/ttt/issues/507
    # - unused       # https://github.com/eugenioenko/ttt/issues/508

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Fprint
      - (io.Closer).Close

run:
  exclude-dirs:
    - vendor
